from __future__ import annotations

from copy import deepcopy

OCEAN_CONDITION_ORDER = [
    "temperature",
    "currents",
    "salinity",
    "oxygen",
    "waves",
    "seaLevel",
]

_OCEAN_CONDITIONS = {
    "temperature": {
        "id": "temperature",
        "label": "Surface temperature",
        "product_id": "BALTICSEA_ANALYSISFORECAST_PHY_003_006",
        "dataset_id": "cmems_mod_bal_phy_anfc_PT1H-i",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "thetao",
        "variables": ["thetao"],
        "units": "degC",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster",
        "value_key": "value_celsius",
        "value_label": "Surface temperature",
        "palette_mode": "temperature",
        "legend_note": "",
        "depth_mode": "surface",
        "time_resolution_label": "Hourly",
    },
    "currents": {
        "id": "currents",
        "label": "Currents",
        "product_id": "BALTICSEA_ANALYSISFORECAST_PHY_003_006",
        "dataset_id": "cmems_mod_bal_phy_anfc_PT15M-i",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "currents",
        "variables": ["uo", "vo"],
        "units": "m/s",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster+particles",
        "value_key": "speed_mps",
        "value_label": "Current speed",
        "palette_mode": "fixed",
        "legend_note": "Particles indicate current direction",
        "depth_mode": "surface",
        "time_resolution_label": "15-minute",
    },
    "salinity": {
        "id": "salinity",
        "label": "Salinity",
        "product_id": "BALTICSEA_ANALYSISFORECAST_PHY_003_006",
        "dataset_id": "cmems_mod_bal_phy_anfc_PT1H-i",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "so",
        "variables": ["so"],
        "units": "PSU",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster",
        "value_key": "value_psu",
        "value_label": "Salinity",
        "palette_mode": "fixed",
        "legend_note": "",
        "depth_mode": "surface",
        "time_resolution_label": "Hourly",
    },
    "oxygen": {
        "id": "oxygen",
        "label": "Bottom dissolved oxygen",
        "product_id": "BALTICSEA_ANALYSISFORECAST_BGC_003_007",
        "dataset_id": "cmems_mod_bal_bgc_anfc_P1D-m",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "o2",
        "variables": ["o2"],
        "units": "mmol/m^3",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster",
        "value_key": "value_mmol_m3",
        "value_label": "Bottom dissolved oxygen",
        "palette_mode": "fixed",
        "legend_note": "Deepest valid model level at each location; not a hypoxia classification",
        "depth_mode": "bottom",
        "time_resolution_label": "Daily",
    },
    "waves": {
        "id": "waves",
        "label": "Waves",
        "product_id": "BALTICSEA_ANALYSISFORECAST_WAV_003_010",
        "dataset_id": "cmems_mod_bal_wav_anfc_PT1H-i",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "waves",
        "variables": ["VHM0", "VMDR", "VTM10"],
        "units": "m",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster+particles",
        "value_key": "significant_height_m",
        "value_label": "Significant wave height",
        "palette_mode": "fixed",
        "legend_note": "Streaks indicate wave propagation direction",
        "depth_mode": "surface",
        "time_resolution_label": "Hourly",
    },
    "seaLevel": {
        "id": "seaLevel",
        "label": "Sea level",
        "product_id": "BALTICSEA_ANALYSISFORECAST_PHY_003_006",
        "dataset_id": "cmems_mod_bal_phy_anfc_PT1H-i",
        "dataset_type": "Modelled analysis and forecast",
        "variable": "zos",
        "variables": ["zos"],
        "units": "m",
        "source_label": "Copernicus Marine model analysis/forecast",
        "render_type": "raster",
        "value_key": "value_m",
        "value_label": "Sea level",
        "palette_mode": "fixed",
        "legend_note": "",
        "depth_mode": "surface",
        "time_resolution_label": "Hourly",
    },
}


def ocean_condition_definitions() -> dict[str, dict[str, object]]:
    return deepcopy(_OCEAN_CONDITIONS)


def ocean_condition_definition(condition_id: str) -> dict[str, object]:
    return deepcopy(_OCEAN_CONDITIONS[condition_id])
